import type { Metadata } from "next";
import { getMockEvent } from "@/lib/mock-event";
import { getMoodTemplate } from "@/lib/mood-templates";
import { EventRsvpFlow } from "@/components/rsvp/event-rsvp-flow";

type Props = {
  params: Promise<{ id: string }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  const event = getMockEvent(id);
  const mood = getMoodTemplate(event.mood);

  const formattedDate = new Date(event.datetime).toLocaleDateString("ko-KR", {
    month: "long",
    day: "numeric",
    weekday: "short",
  });

  return {
    title: `${event.title} — 모먼트`,
    description: `${formattedDate} · ${event.location}`,
    openGraph: {
      title: event.title,
      description: `${formattedDate} · ${event.location}`,
      type: "website",
      siteName: "모먼트",
      // OG image is auto-generated by opengraph-image.tsx (Satori)
    },
    other: {
      // Kakao OG tags
      "og:title": event.title,
      "og:description": `${formattedDate} · ${event.location}`,
      ...(mood ? { "theme-color": mood.colorTheme.primary } : {}),
    },
  };
}

export default async function EventPage({ params }: Props) {
  const { id } = await params;
  const event = getMockEvent(id);

  return <EventRsvpFlow event={event} />;
}
